url: https://carpentries.org
baseurl: /

# Site settings
title: The Carpentries 
email: team@carpentries.org
description: "We teach foundational computational and data science skills to researchers"


# Team names, titles and social links
people:
- name: Tracy Teal
  pic: 1
  position: Executive Director
  social:
    - title: twitter
      url: https://twitter.com/tracykteal
    - title: facebook
      url: https://www.facebook.com/carpentries

- name: Jonah Duckles
  pic: 2
  position: Director of Membership and Technology
  social:
    - title: twitter
      url: https://twitter.com/jduckles
    - title: facebook
      url: https://www.facebook.com/carpentries

- name: Erin Becker
  pic: 3
  position: Associate Director
  social:
    - title: twitter
      url: https://twitter.com/ErinSBecker
    - title: facebook
      url: https://www.facebook.com/carpentries
      
- name: Kari L. Jordan
  pic: 4
  position: Director of Assessment and Community Equity
  social:
    - title: twitter
      url: https://twitter.com/kariljordan
    - title: facebook
      url: https://www.facebook.com/carpentries  
      
- name: Belinda Weaver
  pic: 5
  position: Community Communications Development Lead
  social:
    - title: twitter
      url: https://twitter.com/cloudaus
    - title: github
      url: https://github.com/weaverbel
    - title: facebook
      url: https://www.facebook.com/carpentries

- name: Maneesha Sane
  pic: 6
  position: Program Manager
  social:
    - title: twitter
      url: https://twitter.com/maneeshasane
    - title: facebook
      url: https://www.facebook.com/carpentries
      
- name: SherAaron Hurt
  pic: 7
  position: Workshop Administrator
  social:
    - title: twitter
      url: https://twitter.com/SherAaronHurt
    - title: facebook
      url: https://www.facebook.com/carpentries

- name: Elizabeth Williams
  pic: 8
  position: Business Administrator
  social:
    - title: twitter
      url: https://twitter.com/ecwilliams8
    - title: facebook
      url: https://www.facebook.com/carpentries
           
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thecarpentries
  - title: github
    url: https://github.com/carpentries/
  - title: facebook
    url: https://www.facebook.com/carpentries/
  - title: slack
    url: https://swc-slack-invite.herokuapp.com/

# Postal address (add as many lines as necessary)
address:
  - line: Davis, California

# Build settings
markdown: kramdown
permalink: pretty
