url: https://carpentries.org
baseurl: /

# Site settings
title: The Carpentries 
email: team@carpentries.org
description: "We teach foundational computational and data science skills to researchers"

# Team names, titles and social links
people:
- name: Tracy Teal
  pic: 1
  position: Executive Director
  social:
    - title: twitter
      url: https://twitter.com/tracykteal
    - title: github
      url: https://github.com/tracykteal

- name: Erin Becker
  pic: 2
  position: Associate Director
  social:
    - title: twitter
      url: https://twitter.com/ErinSBecker
    - title: github
      url: https://github.com/erinbecker

- name: Jonah Duckles
  pic: 3
  position: Director of Membership and Technology
  social:
    - title: twitter
      url: https://twitter.com/jduckles
    - title: github
      url: https://github.com/jduckles
      
- name: Kari L. Jordan
  pic: 4
  position: Director of Assessment and Community Equity
  social:
    - title: twitter
      url: https://twitter.com/drkariljordan
    - title: github
      url: https://github.com/kariljordan
      
- name: Belinda Weaver
  pic: 5
  position: Community and Communications Lead
  social:
    - title: twitter
      url: https://twitter.com/cloudaus
    - title: github
      url: https://github.com/weaverbel
    - title: linkedin
      url: https://www.linkedin.com/in/belinda-weaver-8525526/

- name: François Michonneau 
  pic: 6
  position: Curriculum Development Lead
  social:
    - title: twitter
      url: https://twitter.com/fmic_
    - title: github
      url: https://github.com/fmichonneau
      
- name: Maneesha Sane
  pic: 7
  position: Program Manager
  social:
    - title: twitter
      url: https://twitter.com/maneeshasane
    - title: github   
      url: https://github.com/maneesha
      
- name: SherAaron Hurt
  pic: 8
  position: Workshop Administrator
  social:
    - title: twitter
      url: https://twitter.com/SherAaronHurt
    - title: github   
      url: https://github.com/sheraaron   

- name: Elizabeth Williams
  pic: 9
  position: Business Administrator
  social:
    - title: twitter
      url: https://twitter.com/ecwilliams8
     
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thecarpentries
  - title: github
    url: https://github.com/carpentries/
  - title: facebook
    url: https://www.facebook.com/carpentries/
  - title: slack
    url: https://swc-slack-invite.herokuapp.com/

# Postal address (add as many lines as necessary)
address:
  - line: The Carpentries c/o Community Initiatives,  
  - line: 354 Pine Street, Suite 700,
  - line: San Francisco, California 94104

# Build settings
markdown: kramdown
permalink: pretty
