url: https://carpentries.org
baseurl: /

# Site settings
title: The Carpentries 
email: team@carpentries.org
description: "We teach foundational computational and data science skills to researchers"


# Team names, titles and social links
people:
- name: Jonah Duckles
  pic: 1
  position: Executive Director
  social:
    - title: twitter
      url: https://twitter.com/jduckles
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Belinda Weaver
  pic: 2
  position: Community Development Lead
  social:
    - title: twitter
      url: https://twitter.com/cloudaus
    - title: github
      url: https://github.com/weaverbel
    - title: facebook
      url: https://www.facebook.com/carpentries

- name: Maneesha Sane
  pic: 3
  position: Program Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/swcarpentry
  - title: github
    url: https://github.com/swcarpentry/
  - title: facebook
    url: https://www.facebook.com/carpentries/
  - title: slack
    url: https://swc-slack-invite.herokuapp.com/

# Postal address (add as many lines as necessary)
address:
  - line: Brisbane, Australia

# Build settings
markdown: kramdown
permalink: pretty
